### ISSUE TITLE
Error running transpose tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/kotlin-test-runner#61]
When running the tests for the `transpose` exercise with the following code:

```kotlin
object Transpose {

     fun transpose(input: List<String>): List<String> {
        val longestLength = input.map { it.length }.max()
		return List(longestLength) { index -> 
            input
                .map { it.padEnd(longestLength) }
        	    .map { it[index] }
                .joinToString(separator = "")
        }.map { it.trimEnd() }
    }
}
```

The test runner fails with:

```
Picked up JAVA_TOOL_OPTIONS: -Xss128m -Xms256m -Xmx2G -XX:+UseG1GC
Exception in thread "main" java.lang.NullPointerException: attribute(...) must not be null
	at utils.junit.ParserKt.get(parser.kt:97)
	at utils.junit.ParserKt.asError(parser.kt:51)
	at utils.junit.ParserKt.asTestCase(parser.kt:37)
	at utils.junit.ParserKt.asTestSuit(parser.kt:26)
	at utils.junit.ParserKt.parseJUnit4Results(parser.kt:14)
	at exercism.kotlin.autotests.executor.ExecutorKt.buildExecutionResult(executor.kt:101)
	at exercism.kotlin.autotests.executor.ExecutorKt.executor(executor.kt:12)
	at exercism.kotlin.autotests.runner.MainKt$main$result$1.invoke(main.kt:28)
	at exercism.kotlin.autotests.runner.MainKt$main$result$1.invoke(main.kt:28)
	at exercism.kotlin.autotests.executor.EnvironmentKt.executeOnEnvironment(environment.kt:16)
	at exercism.kotlin.autotests.runner.MainKt.main(main.kt:28)

```

@ErwinOlie Do you have any idea?

**Comment by ErwinOlie** [comment]
There seems to be a problem with parsing the junit4 test report. Can you post the content of the TESTsomething.xml file which is produced after running the test?

**Comment by ErikSchierboom** [comment]
I don't see the test file. Where should that be located?

**Comment by ErikSchierboom** [comment]
@ErwinOlie I can't see the file. Where is it written to the file system?

**Comment by ErwinOlie** [comment]
It should be somewhere in the /build/ directory after trying to run the test. I'm not sure about the exact location

**Comment by ErikSchierboom** [comment]
@ErwinOlie I don't see it. Maybe it isn't created because of the error?

**Comment by Adithyan1919** [comment]
Change .max() to .maxOrNull() ?: 0 to prevent null values 
val longestLength = input.map { it.length }.maxOrNull() ?: 0
Check if the test output files (like /results.json  or JUnit XML for generic runners) are present after running tests.
If missing, investigate for compilation errors, missing dependencies, or failing test setup.
